#!/bin/bash
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
BOLD=$(tput bold)
RESET=$(tput sgr0)
DISPLAY_SCALING=""
CURSOR_SIZE=""

set_display_scaling() {
    local input="$2"
    if [[ "$input" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
        DISPLAY_SCALING=$(printf "%.2f" "$input")

        if (( $(awk "BEGIN {print ($DISPLAY_SCALING < 0.25)}") )); then
            echo "${RED}Warning: DISPLAY_SCALING below 0.25, resetting to 1.0${RESET}"
            DISPLAY_SCALING=1.0
        elif (( $(awk "BEGIN {print ($DISPLAY_SCALING > 4.0)}") )); then
            echo "${RED}Warning: DISPLAY_SCALING above 4.0, resetting to 4.0${RESET}"
            DISPLAY_SCALING=4.0
        fi

        echo "${GREEN}Display scaling set to $DISPLAY_SCALING${RESET}"
        export ELECTRON_FORCE_DEVICE_SCALE_FACTOR=$DISPLAY_SCALING
    else
        echo "${RED}Error: DISPLAY_SCALING must be a number between 0.25 and 4.0 (e.g., 1, 1.5, 2.25)${RESET}"
        return 1
    fi
}

set_cursor_scaling() {
    if ! [[ "$1" =~ ^[0-9]+$ ]]; then
        echo "${RED}Error: Cursor size must be an integer.${RESET}"
        return 1
    fi

    CURSOR_SIZE=$1

    if (( CURSOR_SIZE < 8 )); then
        echo "${YELLOW}Warning: Cursor size below 8, resetting to 8.${RESET}"
        CURSOR_SIZE=8
    elif (( CURSOR_SIZE > 200 )); then
        echo "${YELLOW}Warning: Cursor size above 200, resetting to 200.${RESET}"
        CURSOR_SIZE=200
    fi

    echo "${GREEN}Cursor size set to $CURSOR_SIZE${RESET}"
    export XCURSOR_SIZE=$CURSOR_SIZE
}

show_help() {
    echo "${MAGENTA}"
    echo "Commands with examples:"
    echo "aurora              # show current display and cursor values
    echo "aurora display 1.0  # Set display scaling factor (0.25 - 4.0.)"
    echo "aurora cursor 32    # Set cursor size (8 - 200)"
    echo "aurora help         # Show help"
    echo ""
    echo "flatpak --help"
    echo "flatpak search visualstudio"
    echo "flatpak install com.visualstudio.code"
    echo "flatpak --command=sh com.visualstudio.code"
    echo "/app/bin/code --no-sandbox --no-zygote --disable-gpu-sandbox --disable-features=UsePortal"
    echo "${RESET}"
   
}


case "$1" in
    display)
        set_display_scaling "$2"
        ;;
    cursor)   
        ;;

        ;;
   --h|-h|h|--help|-help|help)
        show_help
        ;;
    ""|status)
        if [[ -z "$ELECTRON_FORCE_DEVICE_SCALE_FACTOR" && -z "$XCURSOR_SIZE" ]]; then
            echo "${YELLOW}Status: Not yet applied.${RESET}"
        else
            [[ -n "$ELECTRON_FORCE_DEVICE_SCALE_FACTOR" ]] && \
                echo "${MAGENTA}ELECTRON_FORCE_DEVICE_SCALE_FACTOR = $ELECTRON_FORCE_DEVICE_SCALE_FACTOR${RESET}" || \
                echo "${YELLOW}ELECTRON_FORCE_DEVICE_SCALE_FACTOR not set${RESET}"

            [[ -n "$XCURSOR_SIZE" ]] && \
                echo "${MAGENTA}XCURSOR_SIZE = $XCURSOR_SIZE${RESET}" || \
                echo "${YELLOW}XCURSOR_SIZE not set${RESET}"
        fi
        ;;

    *)
            echo "${RED}Unknown command $1 ${RESET}"
            show_help
            exit 1
        fi
        ;;
esac
